-- MySQL Script generated by MySQL Workbench
-- Thu Dec  1 09:50:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zsp-sklep
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zsp-sklep
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zsp-sklep` DEFAULT CHARACTER SET utf8 ;
USE `zsp-sklep` ;

-- -----------------------------------------------------
-- Table `zsp-sklep`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zsp-sklep`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `is_admin` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zsp-sklep`.`Offers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zsp-sklep`.`Offers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `seller` INT NULL,
  `buyer` INT NULL,
  `created_at` DATE NOT NULL,
  `sold_at` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zsp-sklep`.`Offers_has_Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zsp-sklep`.`Offers_has_Users` (
  `Offers_id` INT NOT NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`Offers_id`, `Users_id`),
  CONSTRAINT `fk_Offers_has_Users_Offers`
    FOREIGN KEY (`Offers_id`)
    REFERENCES `zsp-sklep`.`Offers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offers_has_Users_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `zsp-sklep`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zsp-sklep`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zsp-sklep`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `price`, `description`, `name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zsp-sklep`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zsp-sklep`.`Orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `products_id` INT NOT NULL,
  `products_price` VARCHAR(45) NOT NULL,
  `products_description` VARCHAR(45) NOT NULL,
  `products_name` VARCHAR(45) NOT NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `products_id`, `products_price`, `products_description`, `products_name`, `Users_id`),
  CONSTRAINT `fk_Orders_products1`
    FOREIGN KEY (`products_id` , `products_price` , `products_description` , `products_name`)
    REFERENCES `zsp-sklep`.`products` (`id` , `price` , `description` , `name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `zsp-sklep`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
