-- MySQL Script generated by MySQL Workbench
-- Wed Nov 30 15:07:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zsp-sklep
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zsp-sklep
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zsp-sklep` DEFAULT CHARACTER SET utf8 ;
USE `zsp-sklep` ;

-- -----------------------------------------------------
-- Table `zsp-sklep`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zsp-sklep`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `is_admin` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zsp-sklep`.`Offers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zsp-sklep`.`Offers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `seller` INT NULL,
  `buyer` INT NULL,
  `created_at` DATE NOT NULL,
  `sold_at` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zsp-sklep`.`Offers_has_Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zsp-sklep`.`Offers_has_Users` (
  `Offers_id` INT NOT NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`Offers_id`, `Users_id`),
  CONSTRAINT `fk_Offers_has_Users_Offers`
    FOREIGN KEY (`Offers_id`)
    REFERENCES `zsp-sklep`.`Offers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offers_has_Users_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `zsp-sklep`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
